### ISSUE TITLE
Investigate idm plugin test failures

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#72]
http://idm-bamboo:8085/browse/IL-CT-54/test
exceptions.TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ckan/src/ckan/ckanext/idm/tests/test_plugin.py", line 223, in test_create_resource_type
    u'purpose': rt
  File "/home/ckan/src/ckan/ckan/tests/helpers.py", line 106, in call_action
    return logic.get_action(action_name)(context=context, data_dict=kwargs)
  File "/home/ckan/src/ckan/ckan/logic/__init__.py", line 466, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/ckan/src/ckan/ckan/logic/action/create.py", line 170, in package_create
    package_plugin, context, data_dict, schema, 'package_create')
  File "/home/ckan/src/ckan/ckan/lib/plugins.py", line 291, in plugin_validate
    result = plugin.validate(context, data_dict, schema, action)
  File "/home/ckan/src/ckan/ckanext/scheming/plugins.py", line 270, in validate
    return navl_validate(data_dict, schema, context)
  File "/home/ckan/src/ckan/ckan/lib/navl/dictization_functions.py", line 297, in validate
    converted_data, errors = _validate(flattened, schema, validators_context)
  File "/home/ckan/src/ckan/ckan/lib/navl/dictization_functions.py", line 346, in _validate
    convert(converter, key, converted_data, errors, context)
  File "/home/ckan/src/ckan/ckan/lib/navl/dictization_functions.py", line 236, in convert
    value = converter(converted_data.get(key))
  File "/home/ckan/src/ckan/ckanext/scheming/validation.py", line 38, in validator
    choices = sh.scheming_field_choices(field)
  File "/home/ckan/src/ckan/ckanext/scheming/helpers.py", line 67, in scheming_field_choices
    return choices_fn(field)
  File "/home/ckan/src/ckan/ckanext/idm/helpers.py", line 9, in get_diseases_choices
    return _to_choices_helper_format(get_diseases())
  File "/home/ckan/src/ckan/ckanext/idm/helpers.py", line 17, in _to_choices_helper_format
    choices = [{u'value': str(v), u'label': v} for v in list]
TypeError: 'NoneType' object is not iterable

**Comment by MeWu-IDM** [comment]
this is due to vocabulary setup
